Search.appendIndex(
    [
                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\App",
            "name": "App",
            "summary": "Integrates\u0020the\u0020libraries\u0020features\ninto\u0020an\u0020application.",
            "url": "classes/Efortmeyer-Polar-Api-App.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\App\u003A\u003Aconfigure\u0028\u0029",
            "name": "configure",
            "summary": "Creates\u0020an\u0020app\u0020object\u0020using\nthe\u0020provided\u0020configuration.",
            "url": "classes/Efortmeyer-Polar-Api-App.html#method_configure"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\App\u003A\u003AsetUpRoutes\u0028\u0029",
            "name": "setUpRoutes",
            "summary": "Maps\u0020routes\u0020to\u0020handlers.",
            "url": "classes/Efortmeyer-Polar-Api-App.html#method_setUpRoutes"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\App\u003A\u003AsetUpRootTemplate\u0028\u0029",
            "name": "setUpRootTemplate",
            "summary": "Sets\u0020up\u0020root\u0020template.",
            "url": "classes/Efortmeyer-Polar-Api-App.html#method_setUpRootTemplate"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\App\u003A\u003AsetUpStorage\u0028\u0029",
            "name": "setUpStorage",
            "summary": "Sets\u0020up\u0020data\u0020storage.",
            "url": "classes/Efortmeyer-Polar-Api-App.html#method_setUpStorage"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\App\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Applies\u0020the\u0020request\u0020handler\u0020for\u0020the\nrequest\u0020uri\u0020in\u0020the\u0020configuration.",
            "url": "classes/Efortmeyer-Polar-Api-App.html#method_run"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\App\u003A\u003AROOT_PATH",
            "name": "ROOT_PATH",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-App.html#constant_ROOT_PATH"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\App\u003A\u003AFAVICON_PATH",
            "name": "FAVICON_PATH",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-App.html#constant_FAVICON_PATH"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\AppConfigInterface",
            "name": "AppConfigInterface",
            "summary": "Provides\u0020support\u0020for\u0020configuring\u0020the\u0020app.",
            "url": "classes/Efortmeyer-Polar-Api-AppConfigInterface.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\AppConfigInterface\u003A\u003AgetAll\u0028\u0029",
            "name": "getAll",
            "summary": "Retrieves\u0020the\u0020attribute\u0020configuration.",
            "url": "classes/Efortmeyer-Polar-Api-AppConfigInterface.html#method_getAll"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Attributes\\AttributeInterface",
            "name": "AttributeInterface",
            "summary": "Provides\u0020a\u0020way\u0020to\u0020configure\u0020objects\u0020using\u0020Attributes.",
            "url": "classes/Efortmeyer-Polar-Api-Attributes-AttributeInterface.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Attributes\\AttributeInterface\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "Makes\u0020the\u0020Attribute\u0020callable.",
            "url": "classes/Efortmeyer-Polar-Api-Attributes-AttributeInterface.html#method___invoke"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Attributes\\Config\\AttributeConfigInterface",
            "name": "AttributeConfigInterface",
            "summary": "Provides\u0020a\u0020way\u0020to\u0020retrieve\nmetadata\u0020for\u0020an\u0020attribute.",
            "url": "classes/Efortmeyer-Polar-Api-Attributes-Config-AttributeConfigInterface.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Attributes\\Config\\AttributeConfigInterface\u003A\u003AgetConstructorArgType\u0028\u0029",
            "name": "getConstructorArgType",
            "summary": "Provides\u0020the\u0020contructor\u0020argument\u0020type.",
            "url": "classes/Efortmeyer-Polar-Api-Attributes-Config-AttributeConfigInterface.html#method_getConstructorArgType"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Attributes\\Config\\AttributeConfigInterface\u003A\u003AgetClassNameForDefaultAttribute\u0028\u0029",
            "name": "getClassNameForDefaultAttribute",
            "summary": "Provides\u0020the\u0020class\u0020name\u0020for\u0020the\u0020default\u0020attribute.",
            "url": "classes/Efortmeyer-Polar-Api-Attributes-Config-AttributeConfigInterface.html#method_getClassNameForDefaultAttribute"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Attributes\\Config\\AttributeConfigInterface\u003A\u003AgetConstructorArgTypeForDefault\u0028\u0029",
            "name": "getConstructorArgTypeForDefault",
            "summary": "Provides\u0020the\u0020contructor\u0020argument\u0020type\u0020for\u0020the\u0020default\u0020attribute.",
            "url": "classes/Efortmeyer-Polar-Api-Attributes-Config-AttributeConfigInterface.html#method_getConstructorArgTypeForDefault"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Attributes\\Config\\AttributeConfigInterface\u003A\u003AforType\u0028\u0029",
            "name": "forType",
            "summary": "Use\u0020to\u0020determine\u0020if\u0020the\u0020attribute\u0020is\u0020for\u0020a\u0020specified\u0020type.",
            "url": "classes/Efortmeyer-Polar-Api-Attributes-Config-AttributeConfigInterface.html#method_forType"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Attributes\\Config\\AttributeConfigInterface\u003A\u003AisConfiguredForClass\u0028\u0029",
            "name": "isConfiguredForClass",
            "summary": "Use\u0020to\u0020deterimine\u0020if\u0020the\u0020attribute\u0020is\u0020configured\u0020for\u0020any\u0020class.",
            "url": "classes/Efortmeyer-Polar-Api-Attributes-Config-AttributeConfigInterface.html#method_isConfiguredForClass"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Attributes\\Config\\Collection",
            "name": "Collection",
            "summary": "Use\u0020to\u0020register\u0020attribute\u0020configurations.",
            "url": "classes/Efortmeyer-Polar-Api-Attributes-Config-Collection.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Attributes\\Config\\Collection\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Adds\u0020a\u0020configuration\u0020to\u0020this\u0020registry.",
            "url": "classes/Efortmeyer-Polar-Api-Attributes-Config-Collection.html#method_add"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Attributes\\Config\\Collection\u003A\u003Afilter\u0028\u0029",
            "name": "filter",
            "summary": "Applies\u0020a\u0020filtering\u0020function\u0020to\u0020this\u0020registry.",
            "url": "classes/Efortmeyer-Polar-Api-Attributes-Config-Collection.html#method_filter"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Attributes\\Config\\Collection\u003A\u003Amap\u0028\u0029",
            "name": "map",
            "summary": "Transforms\u0020each\u0020configuration\u0020in\u0020this\u0020registry\u0020by\napplying\u0020the\u0020given\u0020mapping\u0020function.",
            "url": "classes/Efortmeyer-Polar-Api-Attributes-Config-Collection.html#method_map"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Attributes\\Config\\Collection\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Converts\u0020this\u0020object\u0020into\u0020an\u0020array.",
            "url": "classes/Efortmeyer-Polar-Api-Attributes-Config-Collection.html#method_toArray"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Attributes\\Config\\Key",
            "name": "Key",
            "summary": "Use\u0020to\u0020register\u0020attribute\u0020configurations.",
            "url": "classes/Efortmeyer-Polar-Api-Attributes-Config-Key.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Attributes\\Config\\Key\u003A\u003AgetKey\u0028\u0029",
            "name": "getKey",
            "summary": "Returns\u0020the\u0020string\u0020representation\u0020of\u0020this\u0020key.",
            "url": "classes/Efortmeyer-Polar-Api-Attributes-Config-Key.html#method_getKey"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Comparable",
            "name": "Comparable",
            "summary": "Provides\u0020support\u0020for\u0020equality\u0020comparison.",
            "url": "classes/Efortmeyer-Polar-Api-Comparable.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Comparable\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-Comparable.html#method_equals"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\DataStorage\\CollectionStorageFactory",
            "name": "CollectionStorageFactory",
            "summary": "Provides\u0020a\u0020way\u0020to\u0020create\u0020a\u0020storage\u0020object.",
            "url": "classes/Efortmeyer-Polar-Api-DataStorage-CollectionStorageFactory.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\DataStorage\\CollectionStorageFactory\u003A\u003AgetStorage\u0028\u0029",
            "name": "getStorage",
            "summary": "Retrieves\u0020the\u0020storage\u0020object.",
            "url": "classes/Efortmeyer-Polar-Api-DataStorage-CollectionStorageFactory.html#method_getStorage"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\DataStorage\\CollectionStorageInterface",
            "name": "CollectionStorageInterface",
            "summary": "Provides\u0020a\u0020way\u0020to\u0020interact\u0020with\u0020a\u0020list\u0020of\u0020items.",
            "url": "classes/Efortmeyer-Polar-Api-DataStorage-CollectionStorageInterface.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\DataStorage\\CollectionStorageInterface\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "Saves\u0020an\u0020item\u0020to\u0020a\u0020collection.",
            "url": "classes/Efortmeyer-Polar-Api-DataStorage-CollectionStorageInterface.html#method_save"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\DataStorage\\CollectionStorageInterface\u003A\u003Alist\u0028\u0029",
            "name": "list",
            "summary": "Returns\u0020a\u0020list\u0020of\u0020items.",
            "url": "classes/Efortmeyer-Polar-Api-DataStorage-CollectionStorageInterface.html#method_list"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\DataStorage\\CsvFileStorage",
            "name": "CsvFileStorage",
            "summary": "Use\u0020to\u0020interact\u0020with\u0020a\u0020CSV\u0020file\u0027s\u0020data.",
            "url": "classes/Efortmeyer-Polar-Api-DataStorage-CsvFileStorage.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\DataStorage\\CsvFileStorage\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-DataStorage-CsvFileStorage.html#method___construct"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\DataStorage\\CsvFileStorage\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-DataStorage-CsvFileStorage.html#method___destruct"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\DataStorage\\CsvFileStorage\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "Saves\u0020a\u0020record\u0020to\u0020a\u0020CSV\u0020file.",
            "url": "classes/Efortmeyer-Polar-Api-DataStorage-CsvFileStorage.html#method_save"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\DataStorage\\CsvFileStorage\u003A\u003Alist\u0028\u0029",
            "name": "list",
            "summary": "Returns\u0020a\u0020list\u0020of\u0020records\u0020from\u0020a\u0020CSV\u0020file.",
            "url": "classes/Efortmeyer-Polar-Api-DataStorage-CsvFileStorage.html#method_list"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\InMemoryAppConfig",
            "name": "InMemoryAppConfig",
            "summary": "Provides\u0020an\u0020in\u0020memory\u0020interface\u0020for\u0020configuration\u0020the\u0020application.",
            "url": "classes/Efortmeyer-Polar-Api-InMemoryAppConfig.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\InMemoryAppConfig\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-InMemoryAppConfig.html#method___construct"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\InMemoryAppConfig\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Add\u0020or\u0020override\u0020an\u0020attribute\u0020configuration.",
            "url": "classes/Efortmeyer-Polar-Api-InMemoryAppConfig.html#method_add"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\InMemoryAppConfig\u003A\u003AgetAll\u0028\u0029",
            "name": "getAll",
            "summary": "Return\u0020the\u0020all\u0020registered\u0020attribute\u0020configurations.",
            "url": "classes/Efortmeyer-Polar-Api-InMemoryAppConfig.html#method_getAll"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Model",
            "name": "Model",
            "summary": "Represents\u0020a\u0020unit\u0020of\u0020data.",
            "url": "classes/Efortmeyer-Polar-Api-Model.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Model\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "Determines\u0020if\u0020the\u0020object\u0020is\u0020equal\u0020to\u0020another.",
            "url": "classes/Efortmeyer-Polar-Api-Model.html#method_equals"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Rendering\\Files\\File",
            "name": "File",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-Rendering-Files-File.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Rendering\\Files\\File\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-Rendering-Files-File.html#method___construct"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Rendering\\Files\\File\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Displays\u0020the\u0020file.",
            "url": "classes/Efortmeyer-Polar-Api-Rendering-Files-File.html#method_render"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Rendering\\Files\\HtmlFile",
            "name": "HtmlFile",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-Rendering-Files-HtmlFile.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Rendering\\Files\\IcoFile",
            "name": "IcoFile",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-Rendering-Files-IcoFile.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Rendering\\TemplateContext",
            "name": "TemplateContext",
            "summary": "Represents\u0020an\u0020object\u0020used\u0020in\u0020a\u0020template.",
            "url": "classes/Efortmeyer-Polar-Api-Rendering-TemplateContext.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\RequestHandler",
            "name": "RequestHandler",
            "summary": "Provides\u0020common\u0020functionality\u0020for\nrequest\u0020handlers.",
            "url": "classes/Efortmeyer-Polar-Api-RequestHandler.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\RequestHandler\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "Provides\u0020a\u0020way\u0020to\u0020apply\u0020the\u0020request\u0020handler.",
            "url": "classes/Efortmeyer-Polar-Api-RequestHandler.html#method___invoke"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\UIElements\\Banner",
            "name": "Banner",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-UIElements-Banner.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\UIElements\\Banner\u003A\u003AgetStyle\u0028\u0029",
            "name": "getStyle",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-UIElements-Banner.html#method_getStyle"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\UIElements\\Banner\u003A\u003AgetMessage\u0028\u0029",
            "name": "getMessage",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-UIElements-Banner.html#method_getMessage"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\UIElements\\DateFormControl",
            "name": "DateFormControl",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-UIElements-DateFormControl.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\UIElements\\ErrorBanner",
            "name": "ErrorBanner",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-UIElements-ErrorBanner.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\UIElements\\ErrorBanner\u003A\u003AgetMessage\u0028\u0029",
            "name": "getMessage",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-UIElements-ErrorBanner.html#method_getMessage"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\UIElements\\Form",
            "name": "Form",
            "summary": "Represents\u0020an\u0020object\u0020used\u0020in\u0020a\u0020template.",
            "url": "classes/Efortmeyer-Polar-Api-UIElements-Form.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\UIElements\\Form\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-UIElements-Form.html#method___construct"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\UIElements\\Form\u003A\u003AgetModel\u0028\u0029",
            "name": "getModel",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-UIElements-Form.html#method_getModel"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\UIElements\\Form\u003A\u003Asubmit\u0028\u0029",
            "name": "submit",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-UIElements-Form.html#method_submit"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\UIElements\\Form\u003A\u003AgetTextInputs\u0028\u0029",
            "name": "getTextInputs",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-UIElements-Form.html#method_getTextInputs"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\UIElements\\Form\u003A\u003AgetTextAreaInputs\u0028\u0029",
            "name": "getTextAreaInputs",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-UIElements-Form.html#method_getTextAreaInputs"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\UIElements\\Form\u003A\u003AgetDateInputs\u0028\u0029",
            "name": "getDateInputs",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-UIElements-Form.html#method_getDateInputs"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\UIElements\\Form\u003A\u003AgetHiddenInputs\u0028\u0029",
            "name": "getHiddenInputs",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-UIElements-Form.html#method_getHiddenInputs"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\UIElements\\Form\u003A\u003AhasErrors\u0028\u0029",
            "name": "hasErrors",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-UIElements-Form.html#method_hasErrors"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\UIElements\\Form\u003A\u003A\u0024banner",
            "name": "banner",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-UIElements-Form.html#property_banner"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\UIElements\\FormControl",
            "name": "FormControl",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-UIElements-FormControl.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\UIElements\\FormControl\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-UIElements-FormControl.html#method_create"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\UIElements\\FormControl\u003A\u003AgetErrorStyling\u0028\u0029",
            "name": "getErrorStyling",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-UIElements-FormControl.html#method_getErrorStyling"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\UIElements\\FormControl\u003A\u003AgetErrorMesage\u0028\u0029",
            "name": "getErrorMesage",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-UIElements-FormControl.html#method_getErrorMesage"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\UIElements\\FormControl\u003A\u003AgetLabel\u0028\u0029",
            "name": "getLabel",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-UIElements-FormControl.html#method_getLabel"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\UIElements\\FormControl\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-UIElements-FormControl.html#method_getName"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\UIElements\\FormControl\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-UIElements-FormControl.html#method_getValue"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\UIElements\\FormControl\u003A\u003AisInvalid\u0028\u0029",
            "name": "isInvalid",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-UIElements-FormControl.html#method_isInvalid"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\UIElements\\HiddenFormControl",
            "name": "HiddenFormControl",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-UIElements-HiddenFormControl.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\UIElements\\NumberFormControl",
            "name": "NumberFormControl",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-UIElements-NumberFormControl.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\UIElements\\SuccessBanner",
            "name": "SuccessBanner",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-UIElements-SuccessBanner.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\UIElements\\SuccessBanner\u003A\u003AgetMessage\u0028\u0029",
            "name": "getMessage",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-UIElements-SuccessBanner.html#method_getMessage"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\UIElements\\TextAreaFormControl",
            "name": "TextAreaFormControl",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-UIElements-TextAreaFormControl.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\UIElements\\TextFormControl",
            "name": "TextFormControl",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Api-UIElements-TextFormControl.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Validation\\ValidationInterface",
            "name": "ValidationInterface",
            "summary": "Provides\u0020a\u0020way\u0020to\u0020validate\u0020a\u0020field.",
            "url": "classes/Efortmeyer-Polar-Api-Validation-ValidationInterface.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Validation\\ValidationInterface\u003A\u003AgetErrorMessage\u0028\u0029",
            "name": "getErrorMessage",
            "summary": "Returns\u0020the\u0020error\u0020message\u0020for\u0020an\u0020invalid\u0020field.",
            "url": "classes/Efortmeyer-Polar-Api-Validation-ValidationInterface.html#method_getErrorMessage"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Validation\\ValidationInterface\u003A\u003AisValid\u0028\u0029",
            "name": "isValid",
            "summary": "Determines\u0020if\u0020the\u0020field\u0020is\u0020invalid.",
            "url": "classes/Efortmeyer-Polar-Api-Validation-ValidationInterface.html#method_isValid"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Attributes\\Config\\ConstructorArgs",
            "name": "ConstructorArgs",
            "summary": "Use\u0020to\u0020provide\u0020metadata\u0020about\u0020the\u0020attribute\nto\u0020the\u0020parser.",
            "url": "classes/Efortmeyer-Polar-Core-Attributes-Config-ConstructorArgs.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Attributes\\Config\\ConstructorArgsNone",
            "name": "ConstructorArgsNone",
            "summary": "Tells\u0020the\u0020parser\u0020that\u0020the\u0020attribute\u0027s\u0020constructor\nhas\u0020no\u0020arguments.",
            "url": "classes/Efortmeyer-Polar-Core-Attributes-Config-ConstructorArgsNone.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Attributes\\Config\\ConstructorArgsOne",
            "name": "ConstructorArgsOne",
            "summary": "Tells\u0020the\u0020parser\u0020that\u0020the\u0020attribute\u0027s\u0020constructor\ntakes\u0020one\u0020argument.",
            "url": "classes/Efortmeyer-Polar-Core-Attributes-Config-ConstructorArgsOne.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Attributes\\Config\\ConstructorArgsPropertyName",
            "name": "ConstructorArgsPropertyName",
            "summary": "Tells\u0020the\u0020parser\u0020that\u0020the\u0020attribute\u0027s\u0020constructor\nuses\u0020the\u0020name\u0020of\u0020the\u0020property\u0020it\u0020configures\u0020as\u0020it\u0027s\nconstructor\u0020argument.",
            "url": "classes/Efortmeyer-Polar-Core-Attributes-Config-ConstructorArgsPropertyName.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Attributes\\Config\\ConstructorArgsPropertyValue",
            "name": "ConstructorArgsPropertyValue",
            "summary": "Tells\u0020the\u0020parser\u0020that\u0020the\u0020attribute\u0027s\u0020constructor\nuses\u0020the\u0020value\u0020of\u0020the\u0020property\u0020it\u0020configures\u0020as\u0020it\u0027s\nconstructor\u0020argument.",
            "url": "classes/Efortmeyer-Polar-Core-Attributes-Config-ConstructorArgsPropertyValue.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Attributes\\Config\\ConstructorArgsPropertyValueWithSecondArg",
            "name": "ConstructorArgsPropertyValueWithSecondArg",
            "summary": "Tells\u0020the\u0020parser\u0020that\u0020the\u0020attribute\u0027s\u0020constructor\nuses\u0020the\u0020name\u0020of\u0020the\u0020property\u0020it\u0020configures\u0020as\u0020it\u0027s\nfirst\u0020constructor\u0020argument.\u0020\u0020The\u0020second\u0020argument\u0020is\nprovided\u0020in\u0020the\u0020annotation\u0020or\u0020native\u0020attribute.",
            "url": "classes/Efortmeyer-Polar-Core-Attributes-Config-ConstructorArgsPropertyValueWithSecondArg.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Defaults",
            "name": "Defaults",
            "summary": "Holds\u0020default\u0020configuration\u0020values.",
            "url": "classes/Efortmeyer-Polar-Core-Defaults.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Defaults\u003A\u003ADATE_FORMAT",
            "name": "DATE_FORMAT",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Core-Defaults.html#constant_DATE_FORMAT"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Defaults\u003A\u003AFORM_CONTROL_TYPE",
            "name": "FORM_CONTROL_TYPE",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Core-Defaults.html#constant_FORM_CONTROL_TYPE"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Defaults\u003A\u003ACOLUMN_FORMATTER",
            "name": "COLUMN_FORMATTER",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Core-Defaults.html#constant_COLUMN_FORMATTER"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Defaults\u003A\u003ALABEL_FORMATTER",
            "name": "LABEL_FORMATTER",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Core-Defaults.html#constant_LABEL_FORMATTER"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Defaults\u003A\u003AMAX_LENGTH",
            "name": "MAX_LENGTH",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Core-Defaults.html#constant_MAX_LENGTH"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Defaults\u003A\u003AERROR_MESSAGE",
            "name": "ERROR_MESSAGE",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Core-Defaults.html#constant_ERROR_MESSAGE"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Defaults\u003A\u003ASUCCESS_MESSAGE",
            "name": "SUCCESS_MESSAGE",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Core-Defaults.html#constant_SUCCESS_MESSAGE"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Messages",
            "name": "Messages",
            "summary": "Contains\u0020text\u0020for\u0020messages.",
            "url": "classes/Efortmeyer-Polar-Core-Messages.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Messages\u003A\u003AOVERSIZED_VALUE",
            "name": "OVERSIZED_VALUE",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Core-Messages.html#constant_OVERSIZED_VALUE"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Messages\u003A\u003AINVALID_TYPE",
            "name": "INVALID_TYPE",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Core-Messages.html#constant_INVALID_TYPE"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Messages\u003A\u003AUKNOWN_TYPE",
            "name": "UKNOWN_TYPE",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Core-Messages.html#constant_UKNOWN_TYPE"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Parsers\\Annotation\\Constructor",
            "name": "Constructor",
            "summary": "Use\u0020to\u0020parse\u0020an\u0020attribute\u0027s\u0020constructor.",
            "url": "classes/Efortmeyer-Polar-Core-Parsers-Annotation-Constructor.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Parsers\\Annotation\\Constructor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Core-Parsers-Annotation-Constructor.html#method___construct"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Parsers\\Annotation\\Constructor\u003A\u003AtoToken\u0028\u0029",
            "name": "toToken",
            "summary": "Converts\u0020an\u0020annotation\u0020string\u0020to\u0020an\u0020attribute\u0020token.",
            "url": "classes/Efortmeyer-Polar-Core-Parsers-Annotation-Constructor.html#method_toToken"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Parsers\\Annotation\\ConstructorArgsNone",
            "name": "ConstructorArgsNone",
            "summary": "Use\u0020to\u0020parse\u0020a\u0020constructor\u0020with\u0020no\u0020arguments.",
            "url": "classes/Efortmeyer-Polar-Core-Parsers-Annotation-ConstructorArgsNone.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Parsers\\Annotation\\ConstructorArgsOne",
            "name": "ConstructorArgsOne",
            "summary": "Use\u0020to\u0020parse\u0020a\u0020constructor\u0020with\u0020one\u0020argument.",
            "url": "classes/Efortmeyer-Polar-Core-Parsers-Annotation-ConstructorArgsOne.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Parsers\\Annotation\\ConstructorArgsOneWithValue",
            "name": "ConstructorArgsOneWithValue",
            "summary": "Use\u0020to\u0020parse\u0020a\u0020constructor\u0020with\u0020one\u0020argument.",
            "url": "classes/Efortmeyer-Polar-Core-Parsers-Annotation-ConstructorArgsOneWithValue.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Parsers\\Annotation\\Token",
            "name": "Token",
            "summary": "An\u0020intermediate\u0020representation\u0020of\u0020a\u0020parsed\u0020attribute.",
            "url": "classes/Efortmeyer-Polar-Core-Parsers-Annotation-Token.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Parsers\\Annotation\\Token\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Core-Parsers-Annotation-Token.html#method___construct"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Parsers\\Annotation\\Token\u003A\u003AgetArguments\u0028\u0029",
            "name": "getArguments",
            "summary": "Retrieves\u0020the\u0020attribute\u0027s\u0020constructor\u0020arguments.",
            "url": "classes/Efortmeyer-Polar-Core-Parsers-Annotation-Token.html#method_getArguments"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Parsers\\Annotation\\Token\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "Retrieves\u0020the\u0020attribute\u0027s\u0020fully\u0020qualified\u0020name.",
            "url": "classes/Efortmeyer-Polar-Core-Parsers-Annotation-Token.html#method_getName"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Parsers\\Annotation\\Token\u003A\u003AnewInstance\u0028\u0029",
            "name": "newInstance",
            "summary": "Creates\u0020the\u0020final\u0020representation\u0020the\u0020token\u0020represents.",
            "url": "classes/Efortmeyer-Polar-Core-Parsers-Annotation-Token.html#method_newInstance"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Parsers\\Annotation\\TypeTag",
            "name": "TypeTag",
            "summary": "Use\u0020to\u0020parse\u0020a\u0020constructor\u0020for\u0020a\u0020type\u0020tag\u0020and\u0020keyword\u0020expression.",
            "url": "classes/Efortmeyer-Polar-Core-Parsers-Annotation-TypeTag.html"
        },                {
            "fqsen": "\\Stringable",
            "name": "Stringable",
            "summary": "",
            "url": "classes/Stringable.html"
        },                {
            "fqsen": "\\Stringable\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Stringable.html#method___toString"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Rendering\\ContentTypes",
            "name": "ContentTypes",
            "summary": "Contains\u0020a\u0020set\u0020of\u0020content\u0020types\u0020for\u0020files\u0020and\u0020streams.",
            "url": "classes/Efortmeyer-Polar-Core-Rendering-ContentTypes.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Rendering\\ContentTypes\u003A\u003AHTML",
            "name": "HTML",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Core-Rendering-ContentTypes.html#constant_HTML"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Rendering\\ContentTypes\u003A\u003AICO",
            "name": "ICO",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Core-Rendering-ContentTypes.html#constant_ICO"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Rendering\\Template",
            "name": "Template",
            "summary": "Provides\u0020a\u0020way\u0020to\u0020bind\u0020a\u0020template\u0020context\u0027s\u0020variables\nto\u0020a\u0020template\u0020file.",
            "url": "classes/Efortmeyer-Polar-Core-Rendering-Template.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Rendering\\Template\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Displays\u0020the\u0020content\u0020of\u0020a\u0020template\u0020file.",
            "url": "classes/Efortmeyer-Polar-Core-Rendering-Template.html#method_render"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\AutomaticDateValue",
            "name": "AutomaticDateValue",
            "summary": "Use\u0020when\u0020an\u0020automatic\u0020date\u0020value\u0020should\u0020be\u0020used.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-AutomaticDateValue.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\AutomaticDateValue\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "Makes\u0020the\u0020Attribute\u0020callable.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-AutomaticDateValue.html#method___invoke"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Column",
            "name": "Column",
            "summary": "Configures\u0020a\u0020property\u0027s\u0020column\u0020name.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Column.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Column\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Column.html#method___construct"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Column\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "Makes\u0020the\u0020Attribute\u0020callable.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Column.html#method___invoke"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Config\\AttributeConfig",
            "name": "AttributeConfig",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Config-AttributeConfig.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Config\\AttributeConfig\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Config-AttributeConfig.html#method___construct"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Config\\AttributeConfig\u003A\u003AgetConstructorArgType\u0028\u0029",
            "name": "getConstructorArgType",
            "summary": "Provides\u0020the\u0020contructor\u0020argument\u0020type.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Config-AttributeConfig.html#method_getConstructorArgType"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Config\\AttributeConfig\u003A\u003AgetClassNameForDefaultAttribute\u0028\u0029",
            "name": "getClassNameForDefaultAttribute",
            "summary": "Provides\u0020the\u0020class\u0020name\u0020for\u0020the\u0020default\u0020attribute.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Config-AttributeConfig.html#method_getClassNameForDefaultAttribute"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Config\\AttributeConfig\u003A\u003AgetConstructorArgTypeForDefault\u0028\u0029",
            "name": "getConstructorArgTypeForDefault",
            "summary": "Provides\u0020the\u0020contructor\u0020argument\u0020type\u0020for\u0020the\u0020default\u0020attribute.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Config-AttributeConfig.html#method_getConstructorArgTypeForDefault"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Config\\AttributeConfig\u003A\u003AisConfiguredForClass\u0028\u0029",
            "name": "isConfiguredForClass",
            "summary": "Use\u0020to\u0020deterimine\u0020if\u0020the\u0020attribute\u0020is\u0020configured\u0020for\u0020any\u0020class.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Config-AttributeConfig.html#method_isConfiguredForClass"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Config\\AttributeConfig\u003A\u003AforType\u0028\u0029",
            "name": "forType",
            "summary": "Use\u0020to\u0020determine\u0020if\u0020the\u0020attribute\u0020is\u0020for\u0020a\u0020specified\u0020type.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Config-AttributeConfig.html#method_forType"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Config\\AutomaticDateValueKey",
            "name": "AutomaticDateValueKey",
            "summary": "Use\u0020to\u0020register\u0020attribute\u0020configurations.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Config-AutomaticDateValueKey.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Config\\AutomaticDateValueKey\u003A\u003AgetKey\u0028\u0029",
            "name": "getKey",
            "summary": "Returns\u0020the\u0020string\u0020representation\u0020of\u0020this\u0020key.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Config-AutomaticDateValueKey.html#method_getKey"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Config\\AutomaticDateValueKey\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Config-AutomaticDateValueKey.html#method___toString"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Config\\ColumnKey",
            "name": "ColumnKey",
            "summary": "Use\u0020to\u0020register\u0020attribute\u0020configurations.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Config-ColumnKey.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Config\\ColumnKey\u003A\u003AgetKey\u0028\u0029",
            "name": "getKey",
            "summary": "Returns\u0020the\u0020string\u0020representation\u0020of\u0020this\u0020key.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Config-ColumnKey.html#method_getKey"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Config\\ColumnKey\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Config-ColumnKey.html#method___toString"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Config\\DateFormatKey",
            "name": "DateFormatKey",
            "summary": "Use\u0020to\u0020register\u0020attribute\u0020configurations.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Config-DateFormatKey.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Config\\DateFormatKey\u003A\u003AgetKey\u0028\u0029",
            "name": "getKey",
            "summary": "Returns\u0020the\u0020string\u0020representation\u0020of\u0020this\u0020key.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Config-DateFormatKey.html#method_getKey"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Config\\DateFormatKey\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Config-DateFormatKey.html#method___toString"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Config\\InputKey",
            "name": "InputKey",
            "summary": "Use\u0020to\u0020register\u0020attribute\u0020configurations.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Config-InputKey.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Config\\InputKey\u003A\u003AgetKey\u0028\u0029",
            "name": "getKey",
            "summary": "Returns\u0020the\u0020string\u0020representation\u0020of\u0020this\u0020key.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Config-InputKey.html#method_getKey"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Config\\InputKey\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Config-InputKey.html#method___toString"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Config\\LabelKey",
            "name": "LabelKey",
            "summary": "Use\u0020to\u0020register\u0020attribute\u0020configurations.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Config-LabelKey.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Config\\LabelKey\u003A\u003AgetKey\u0028\u0029",
            "name": "getKey",
            "summary": "Returns\u0020the\u0020string\u0020representation\u0020of\u0020this\u0020key.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Config-LabelKey.html#method_getKey"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Config\\LabelKey\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Config-LabelKey.html#method___toString"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Config\\MaxLengthKey",
            "name": "MaxLengthKey",
            "summary": "Use\u0020to\u0020register\u0020attribute\u0020configurations.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Config-MaxLengthKey.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Config\\MaxLengthKey\u003A\u003AgetKey\u0028\u0029",
            "name": "getKey",
            "summary": "Returns\u0020the\u0020string\u0020representation\u0020of\u0020this\u0020key.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Config-MaxLengthKey.html#method_getKey"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Config\\MaxLengthKey\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Config-MaxLengthKey.html#method___toString"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Config\\TypeValidationKey",
            "name": "TypeValidationKey",
            "summary": "Use\u0020to\u0020register\u0020attribute\u0020configurations.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Config-TypeValidationKey.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Config\\TypeValidationKey\u003A\u003AgetKey\u0028\u0029",
            "name": "getKey",
            "summary": "Returns\u0020the\u0020string\u0020representation\u0020of\u0020this\u0020key.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Config-TypeValidationKey.html#method_getKey"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Config\\TypeValidationKey\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Config-TypeValidationKey.html#method___toString"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\DateFormat",
            "name": "DateFormat",
            "summary": "Configures\u0020the\u0020format\u0020a\u0020DateTime\u0020property.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-DateFormat.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\DateFormat\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-DateFormat.html#method___construct"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\DateFormat\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "Makes\u0020the\u0020Attribute\u0020callable.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-DateFormat.html#method___invoke"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\DefaultColumn",
            "name": "DefaultColumn",
            "summary": "Configures\u0020the\u0020default\u0020column\u0020format.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-DefaultColumn.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\DefaultColumn\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-DefaultColumn.html#method___construct"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\DefaultColumn\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "Makes\u0020the\u0020Attribute\u0020callable.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-DefaultColumn.html#method___invoke"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\DefaultDateFormat",
            "name": "DefaultDateFormat",
            "summary": "Converts\u0020a\u0020DateTime\u0020property\u0020to\u0020a\u0020string\u0020with\u0020the\ndefault\u0020format.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-DefaultDateFormat.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\DefaultDateFormat\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "Makes\u0020the\u0020Attribute\u0020callable.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-DefaultDateFormat.html#method___invoke"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\DefaultFormControl",
            "name": "DefaultFormControl",
            "summary": "Configures\u0020the\u0020default\u0020form\u0020control\u0020type.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-DefaultFormControl.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\DefaultFormControl\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-DefaultFormControl.html#method___construct"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\DefaultFormControl\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "Makes\u0020the\u0020Attribute\u0020callable.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-DefaultFormControl.html#method___invoke"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\DefaultLabel",
            "name": "DefaultLabel",
            "summary": "Formats\u0020a\u0020label\u0027s\u0020text\u0020using\u0020the\u0020default\u0020format.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-DefaultLabel.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\DefaultLabel\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-DefaultLabel.html#method___construct"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\DefaultLabel\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "Makes\u0020the\u0020Attribute\u0020callable.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-DefaultLabel.html#method___invoke"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\DefaultMaxLength",
            "name": "DefaultMaxLength",
            "summary": "Use\u0020to\u0020validate\u0020that\u0020length\u0020of\u0020a\u0020field\u0027s\u0020value\nis\u0020not\u0020over\u0020the\u0020default\u0020max\u0020length.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-DefaultMaxLength.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\DefaultMaxLength\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-DefaultMaxLength.html#method___construct"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\DefaultMaxLength\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "Makes\u0020the\u0020Attribute\u0020callable.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-DefaultMaxLength.html#method___invoke"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Input",
            "name": "Input",
            "summary": "Configures\u0020a\u0020property\u0020to\u0020a\u0020given\u0020form\u0020control\u0020type.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Input.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Input\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Input.html#method___construct"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Input\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "Makes\u0020the\u0020Attribute\u0020callable.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Input.html#method___invoke"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\InputTypes",
            "name": "InputTypes",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-InputTypes.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\InputTypes\u003A\u003ATEXT",
            "name": "TEXT",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-InputTypes.html#constant_TEXT"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\InputTypes\u003A\u003ATEXTAREA",
            "name": "TEXTAREA",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-InputTypes.html#constant_TEXTAREA"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\InputTypes\u003A\u003ANUMBER",
            "name": "NUMBER",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-InputTypes.html#constant_NUMBER"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\InputTypes\u003A\u003ADATE",
            "name": "DATE",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-InputTypes.html#constant_DATE"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Label",
            "name": "Label",
            "summary": "Configures\u0020the\u0020form\u0020label\u0020text\u0020of\u0020a\u0020property.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Label.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Label\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Label.html#method___construct"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Label\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "Makes\u0020the\u0020Attribute\u0020callable.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-Label.html#method___invoke"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\MaxLength",
            "name": "MaxLength",
            "summary": "Configures\u0020the\u0020max\u0020length\u0020of\u0020a\u0020property\u0027s\u0020value.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-MaxLength.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\MaxLength\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-MaxLength.html#method___construct"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\MaxLength\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "Makes\u0020the\u0020Attribute\u0020callable.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-MaxLength.html#method___invoke"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\None",
            "name": "None",
            "summary": "Provides\u0020\u0060noop\u0060\u0020configuration.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-None.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\None\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "Makes\u0020the\u0020Attribute\u0020callable.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-None.html#method___invoke"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\NoopValidate",
            "name": "NoopValidate",
            "summary": "Provides\u0020\u0060noop\u0060\u0020validation.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-NoopValidate.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\NoopValidate\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "Makes\u0020the\u0020Attribute\u0020callable.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-NoopValidate.html#method___invoke"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\TypeValidation",
            "name": "TypeValidation",
            "summary": "Configures\u0020validation\u0020of\u0020the\u0020type\u0020of\u0020a\u0020property\u0027s\u0020value.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-TypeValidation.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\TypeValidation\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-TypeValidation.html#method___construct"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\TypeValidation\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "Makes\u0020the\u0020Attribute\u0020callable.",
            "url": "classes/Efortmeyer-Polar-Stock-Attributes-TypeValidation.html#method___invoke"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\AutomaticDateField",
            "name": "AutomaticDateField",
            "summary": "Represents\u0020a\u0020date\u0020field\u0020with\u0020and\u0020automatically\ngenerated\u0020value.",
            "url": "classes/Efortmeyer-Polar-Stock-AutomaticDateField.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\AutomaticDateField\u003A\u003A\u0024formControlType",
            "name": "formControlType",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-AutomaticDateField.html#property_formControlType"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\DateField",
            "name": "DateField",
            "summary": "Represents\u0020a\u0020date\u0020field.",
            "url": "classes/Efortmeyer-Polar-Stock-DateField.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\DateField\u003A\u003A\u0024formControlType",
            "name": "formControlType",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-DateField.html#property_formControlType"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Entry",
            "name": "Entry",
            "summary": "Represents\u0020an\u0020item\u0020in\u0020a\u0020collection\u0020or\u0020a\u0020row\u0020in\u0020a\u0020table.",
            "url": "classes/Efortmeyer-Polar-Stock-Entry.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Entry\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Entry.html#method___construct"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Entry\u003A\u003AgetColumnNames\u0028\u0029",
            "name": "getColumnNames",
            "summary": "Returns\u0020the\u0020entry\u0027s\u0020column\u0020names.",
            "url": "classes/Efortmeyer-Polar-Stock-Entry.html#method_getColumnNames"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Entry\u003A\u003AgetPropertyNames\u0028\u0029",
            "name": "getPropertyNames",
            "summary": "Returns\u0020the\u0020model\u0027s\u0020property\u0020names.",
            "url": "classes/Efortmeyer-Polar-Stock-Entry.html#method_getPropertyNames"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Entry\u003A\u003AgetFieldValues\u0028\u0029",
            "name": "getFieldValues",
            "summary": "Returns\u0020the\u0020values\u0020of\u0020the\u0020model\u0027s\u0020fields",
            "url": "classes/Efortmeyer-Polar-Stock-Entry.html#method_getFieldValues"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Entry\u003A\u003AgetFields\u0028\u0029",
            "name": "getFields",
            "summary": "Returns\u0020the\u0020field\u0020metadata",
            "url": "classes/Efortmeyer-Polar-Stock-Entry.html#method_getFields"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Field",
            "name": "Field",
            "summary": "Provides\u0020metadata\u0020for\u0020a\u0020field.",
            "url": "classes/Efortmeyer-Polar-Stock-Field.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Field\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Field.html#method_getValue"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Field\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Create\u0020a\u0020Field.",
            "url": "classes/Efortmeyer-Polar-Stock-Field.html#method_create"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Field\u003A\u003A\u0024label",
            "name": "label",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Field.html#property_label"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Field\u003A\u003A\u0024formControlType",
            "name": "formControlType",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Field.html#property_formControlType"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Field\u003A\u003A\u0024column",
            "name": "column",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Field.html#property_column"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Field\u003A\u003A\u0024propertyName",
            "name": "propertyName",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Field.html#property_propertyName"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Field\u003A\u003A\u0024format",
            "name": "format",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Field.html#property_format"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Field\u003A\u003A\u0024validators",
            "name": "validators",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Field.html#property_validators"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Field\u003A\u003A\u0024value",
            "name": "value",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Field.html#property_value"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\NumberField",
            "name": "NumberField",
            "summary": "Represents\u0020a\u0020number\u0020field.",
            "url": "classes/Efortmeyer-Polar-Stock-NumberField.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\NumberField\u003A\u003A\u0024formControlType",
            "name": "formControlType",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-NumberField.html#property_formControlType"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\PropertyAnnotation",
            "name": "PropertyAnnotation",
            "summary": "Provides\u0020a\u0020way\u0020to\u0020parse\u0020a\u0020class\u0027s\u0020property\u0020attributes.",
            "url": "classes/Efortmeyer-Polar-Stock-PropertyAnnotation.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\PropertyAnnotation\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-PropertyAnnotation.html#method___construct"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\PropertyAnnotation\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "Uses\u0020this\u0020property\u0027s\u0020annotations\u0020to\u0020create\u0020a\u0020list\u0020of\u0020attributes.",
            "url": "classes/Efortmeyer-Polar-Stock-PropertyAnnotation.html#method_parse"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\TextAreaField",
            "name": "TextAreaField",
            "summary": "Represents\u0020a\u0020textarea\u0020field.",
            "url": "classes/Efortmeyer-Polar-Stock-TextAreaField.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\TextAreaField\u003A\u003A\u0024formControlType",
            "name": "formControlType",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-TextAreaField.html#property_formControlType"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\TextField",
            "name": "TextField",
            "summary": "Represents\u0020a\u0020text\u0020field.",
            "url": "classes/Efortmeyer-Polar-Stock-TextField.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\TextField\u003A\u003A\u0024formControlType",
            "name": "formControlType",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-TextField.html#property_formControlType"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Validation\\MaxLength",
            "name": "MaxLength",
            "summary": "Provides\u0020a\u0020way\u0020to\u0020validate\u0020the\u0020maximum\u0020length\u0020of\u0020a\u0020field.",
            "url": "classes/Efortmeyer-Polar-Stock-Validation-MaxLength.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Validation\\MaxLength\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Validation-MaxLength.html#method___construct"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Validation\\MaxLength\u003A\u003AgetErrorMessage\u0028\u0029",
            "name": "getErrorMessage",
            "summary": "Returns\u0020the\u0020error\u0020message\u0020for\u0020an\u0020invalid\u0020field.",
            "url": "classes/Efortmeyer-Polar-Stock-Validation-MaxLength.html#method_getErrorMessage"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Validation\\MaxLength\u003A\u003AisValid\u0028\u0029",
            "name": "isValid",
            "summary": "Determines\u0020if\u0020the\u0020field\u0020is\u0020invalid.",
            "url": "classes/Efortmeyer-Polar-Stock-Validation-MaxLength.html#method_isValid"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Validation\\MaxLength\u003A\u003A\u0024value",
            "name": "value",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Validation-MaxLength.html#property_value"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Validation\\Noop",
            "name": "Noop",
            "summary": "Does\u0020no\u0020validation.",
            "url": "classes/Efortmeyer-Polar-Stock-Validation-Noop.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Validation\\Noop\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Validation-Noop.html#method___construct"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Validation\\Noop\u003A\u003AgetErrorMessage\u0028\u0029",
            "name": "getErrorMessage",
            "summary": "Returns\u0020the\u0020error\u0020message\u0020for\u0020an\u0020invalid\u0020field.",
            "url": "classes/Efortmeyer-Polar-Stock-Validation-Noop.html#method_getErrorMessage"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Validation\\Noop\u003A\u003AisValid\u0028\u0029",
            "name": "isValid",
            "summary": "Determines\u0020if\u0020the\u0020field\u0020is\u0020invalid.",
            "url": "classes/Efortmeyer-Polar-Stock-Validation-Noop.html#method_isValid"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Validation\\ScalarTypes",
            "name": "ScalarTypes",
            "summary": "Contains\u0020a\u0020set\u0020of\u0020values\u0020representing\u0020scalar\u0020types.",
            "url": "classes/Efortmeyer-Polar-Stock-Validation-ScalarTypes.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Validation\\ScalarTypes\u003A\u003ASTRING",
            "name": "STRING",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Validation-ScalarTypes.html#constant_STRING"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Validation\\ScalarTypes\u003A\u003AINTEGER",
            "name": "INTEGER",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Validation-ScalarTypes.html#constant_INTEGER"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Validation\\ScalarTypes\u003A\u003AFLOAT",
            "name": "FLOAT",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Validation-ScalarTypes.html#constant_FLOAT"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Validation\\ScalarTypes\u003A\u003ADOUBLE",
            "name": "DOUBLE",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Validation-ScalarTypes.html#constant_DOUBLE"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Validation\\ScalarTypes\u003A\u003ANULL",
            "name": "NULL",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Validation-ScalarTypes.html#constant_NULL"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Validation\\ScalarTypes\u003A\u003ABOOL",
            "name": "BOOL",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Validation-ScalarTypes.html#constant_BOOL"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Validation\\TypeValidation",
            "name": "TypeValidation",
            "summary": "Provides\u0020a\u0020way\u0020to\u0020validate\u0020a\u0020property\u0027s\u0020type.",
            "url": "classes/Efortmeyer-Polar-Stock-Validation-TypeValidation.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Validation\\TypeValidation\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Validation-TypeValidation.html#method___construct"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Validation\\TypeValidation\u003A\u003AgetErrorMessage\u0028\u0029",
            "name": "getErrorMessage",
            "summary": "Returns\u0020the\u0020error\u0020message\u0020for\u0020an\u0020invalid\u0020field.",
            "url": "classes/Efortmeyer-Polar-Stock-Validation-TypeValidation.html#method_getErrorMessage"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Validation\\TypeValidation\u003A\u003AisValid\u0028\u0029",
            "name": "isValid",
            "summary": "Determines\u0020if\u0020the\u0020field\u0020is\u0020invalid.",
            "url": "classes/Efortmeyer-Polar-Stock-Validation-TypeValidation.html#method_isValid"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Validation\\TypeValidation\u003A\u003A\u0024value",
            "name": "value",
            "summary": "",
            "url": "classes/Efortmeyer-Polar-Stock-Validation-TypeValidation.html#property_value"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Rendering\\HtmlEncoder",
            "name": "HtmlEncoder",
            "summary": "Provides\u0020a\u0020way\u0020to\u0020sanitize\u0020a\u0020template\u0027s\u0020variables.",
            "url": "classes/Efortmeyer-Polar-Core-Rendering-HtmlEncoder.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Rendering\\HtmlEncoder\u003A\u003AencodeProperties\u0028\u0029",
            "name": "encodeProperties",
            "summary": "Recursively\u0020and\u0020immutably\u0020encodes\u0020the\u0020object\u0027s\u0020members.",
            "url": "classes/Efortmeyer-Polar-Core-Rendering-HtmlEncoder.html#method_encodeProperties"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api",
            "name": "Api",
            "summary": "",
            "url": "namespaces/efortmeyer-polar-api.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar",
            "name": "Polar",
            "summary": "",
            "url": "namespaces/efortmeyer-polar.html"
        },                {
            "fqsen": "\\Efortmeyer",
            "name": "Efortmeyer",
            "summary": "",
            "url": "namespaces/efortmeyer.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Attributes",
            "name": "Attributes",
            "summary": "",
            "url": "namespaces/efortmeyer-polar-api-attributes.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Attributes\\Config",
            "name": "Config",
            "summary": "",
            "url": "namespaces/efortmeyer-polar-api-attributes-config.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\DataStorage",
            "name": "DataStorage",
            "summary": "",
            "url": "namespaces/efortmeyer-polar-api-datastorage.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Rendering\\Files",
            "name": "Files",
            "summary": "",
            "url": "namespaces/efortmeyer-polar-api-rendering-files.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Rendering",
            "name": "Rendering",
            "summary": "",
            "url": "namespaces/efortmeyer-polar-api-rendering.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\UIElements",
            "name": "UIElements",
            "summary": "",
            "url": "namespaces/efortmeyer-polar-api-uielements.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Api\\Validation",
            "name": "Validation",
            "summary": "",
            "url": "namespaces/efortmeyer-polar-api-validation.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Attributes\\Config",
            "name": "Config",
            "summary": "",
            "url": "namespaces/efortmeyer-polar-core-attributes-config.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Attributes",
            "name": "Attributes",
            "summary": "",
            "url": "namespaces/efortmeyer-polar-core-attributes.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core",
            "name": "Core",
            "summary": "",
            "url": "namespaces/efortmeyer-polar-core.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Parsers\\Annotation",
            "name": "Annotation",
            "summary": "",
            "url": "namespaces/efortmeyer-polar-core-parsers-annotation.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Parsers",
            "name": "Parsers",
            "summary": "",
            "url": "namespaces/efortmeyer-polar-core-parsers.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Core\\Rendering",
            "name": "Rendering",
            "summary": "",
            "url": "namespaces/efortmeyer-polar-core-rendering.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes",
            "name": "Attributes",
            "summary": "",
            "url": "namespaces/efortmeyer-polar-stock-attributes.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Attributes\\Config",
            "name": "Config",
            "summary": "",
            "url": "namespaces/efortmeyer-polar-stock-attributes-config.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock",
            "name": "Stock",
            "summary": "",
            "url": "namespaces/efortmeyer-polar-stock.html"
        },                {
            "fqsen": "\\Efortmeyer\\Polar\\Stock\\Validation",
            "name": "Validation",
            "summary": "",
            "url": "namespaces/efortmeyer-polar-stock-validation.html"
        }            ]
);
